"""Add foreign key relationship between events and categories

Revision ID: 6f72f241aa57
Revises: bceaea932bd9
Create Date: 2024-10-17 11:32:13.406761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f72f241aa57'
down_revision = 'bceaea932bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('date_of_event')
        batch_op.drop_column('location')
        batch_op.drop_column('description')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('date_of_event', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
