"""Updated Event model to include image_url

Revision ID: d5bfcbb28a50
Revises: c0b8d3fa7284
Create Date: 2024-10-21 08:12:47.550633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bfcbb28a50'
down_revision = 'c0b8d3fa7284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('date_of_event',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_events_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.drop_column('booked_tickets')
        batch_op.drop_column('available_tickets')
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('available_tickets', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('booked_tickets', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_events_category_id_categories'), type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_of_event',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
